### ISSUE TITLE
Console.WindowWidth Issue

### ISSUE THREAD

**Issue by dimanov** [SimoPrG/TeamManticore#1] opened 2015-02-22 07:38 UTC
When starting the game, I've got the following error:
"Unhandled Exception: System.ArgumentOutOfRangeException: The console buffer size must not be less than the current size and position of the console window, nor greater than or equal to Int16.MaxValue.
Parameter name: width
Actual value was 120.
   at System.Console.SetBufferSize(Int32 width, Int32 height)
   at System.Console.set_BufferWidth(Int32 value)
   at FlappyManticore.Core.Main() in c:\Users\dimanov\Documents\Visual Studio 2013\Projects\C# Part II\TeamManticore\Core\Core.cs:
line 38"

The current console width of my console is 160.

**Comment by SimoPrG** [comment] 2015-03-01 23:53
Dear colleague,
Thank you for your concern. We have taken into account your feedback and I believe the issue is currently closed as solved.
If you have any other problems with our application, please, feel free to open another issue.
Thanks and Regards,
Simo

**Closed as completed by SimoPrG** 2015-03-01 23:53 UTC
